pipelines:
  - name: destroy_environment
    steps:
    - name: delete_scaffholding
      type: Bash
      configuration:
       inputResources:
        - name: demo_gitRepo
          trigger: false
       integrations:
        - name: Artifactory
      execution:
       onStart:
        - curl -fL https://getcli.jfrog.io | sh
        - sudo apt-get install -y jq
        - cp jfrog  `which jfrog`
        - retry_command jfrog rt config --url $int_Artifactory_url --user
          $int_Artifactory_user --apikey $int_Artifactory_apikey
          --interactive=false
        - "cd ${res_demo_gitRepo_resourcePath}"
        - "ls -lR"
        - "./scripts/delete_entities.sh"
